### ISSUE TITLE
[Feat] 검색 페이지 구현

### ISSUE THREAD

**Issue by FpRaArNkK** [BookJamm/FE#100]
# 📝 작업 내용
- SearchPageVC의 로직을 Rx로 리팩토링합니다.
- feature/100-SearchPage-Rx 브랜치에서 작업합니다.
- UI 변경사항 발생 시 추가 작업합니다.

## ✔️ To-Do
- [x] SearchPageVC UI 변경사항 재작성
- [x] SearchPageVC 로직 Rx로 변환
- [x] SearchPageVC UI Rx바인딩
- [ ] SearchEnterResultVC UI 변경사항 재작성
- [ ] SearchEnterResultVC 로직 Rx로 변환
- [ ] SearchEnterResultVC UI Rx바인딩

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
1. 검색창 초기화면 작성 필요
2. 서치바 아래의 검색결과 문구에 {text}는 데이터 바인딩 필요
3. 필터링 기능은 검색 결과탭에서만 적용됨
4. 검색/검색결과 페이지는 서점/출판물/모임 모든 카테고리를 검색하는 결과 -> 추가 기획 + 디자인 예정
