### ISSUE TITLE
[Feat] MainPage 구현

### ISSUE THREAD

**Issue by FpRaArNkK** [BookJamm/FE#101]
# 📝 작업 내용
- 새롭게 개편된 MainPage의 UI + 로직을 구현합니다.
- Compositional Layout과 함께 DiffableDataSource or RxDatasource 라이브러리를 통해 구현합니다.
- feature/101-MainPage-Rx 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] MainPage Compositional Layout 제작
- [x] DiffableDataSource 사용 or RxDatasource 추가 -> Diffable로 결정
- [x] 각 Model 정의
- [x] 내부 ReusableView - CategoryButton 작업
- [x] MainPage ViewModel 작업
- [x] MainPage ViewModel - DataSource 바인딩
- [x] MainPage DataProvider 생성
- [x] MainPage의 각 Cell ViewModel 작업, 바인딩
- [x] 각 카테고리별 Cell 생성
- [ ] 최상단 배너 뷰 생성
- [ ] 배너 뷰 이벤트 Rx 연결
- [x] etc

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
to ASK
- [x] 상단 광고배너 -> API로 받아 이미지뷰로 표시? or WebView로 표시? / 광고 n개인 경우, 좌우 Carousel View 구현 필요?
- [x] 카테고리(서점/출판물/모임)별 필터링 기능은 전부 갖고 있는 것? -> 각 카테고리(독립 서점/모임/출판물) 별 필터목록, 소개문구(info) 필요
- [x] 모임 탭에 존재하는 출판물의 장르목록은 고정 or 유동? -> 유동인 경우 장르목록 View가 3배정도 길어졌을 때를 고려해봐야함 -> 폴딩 버튼?
- [x] 출판물 탭의 데이터 셀에 위치한 "인문학"장르 버튼은 회색인 이유가? -> 비활성화된 느낌이 들기도 함. 의견 여쭤보기
- [ ] 알람 버튼엔 미열람 알림 갯수 표시하게 할 것?
- [x]  상단 배너 ~ 카테고리 선택탭까지는 화면 상단 고정?
- [ ] 모임 날짜는 하루로 고정? -> 여러 날인 경우와 1일인 경우 어떻게 표시되는지 확인 필요
---
- [ ] 추후 각 카테고리별 Cell 연결 작업 필요
- [ ] Auth 부분 작업 완료 후 API 연결 작업 필요
- [ ] UIMenu (필터 선택, info버튼)의 폰트, 화살표 문제 해결 필요
- [ ] 초반 BehaviorRelay로 인한 이중 API Call 문제 해결 필요
- [ ] 배너 부분 이벤트 확인 필요
