### ISSUE TITLE
[Feat] 마이 페이지 구현

### ISSUE THREAD

**Issue by FpRaArNkK** [BookJamm/FE#106]
# 📝 작업 내용
- MyPageVC의 로직을 Compositional Layout, Rx로 리팩토링합니다.
- feature/101-MainPage-Rx 브랜치에서 작업합니다.
- 변경사항 발생 시 추가 작업합니다.

## ✔️ To-Do
- [x] MyPage - ProfileView 작성
- [x] MyPage - MyPageHeaderView 작성
- [x] MyPage - MyPageCollectionViewCell 작성
- [x] MyPage Compositional Layout 적용
- [x] MyPage 로직 Rx로 변환

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
0. 로그아웃, 회원 탈퇴 AlertController 구현
1. 프로필 닉네임 변경 화면 구현
2. 비밀번호 변경 화면 구현
3. 회원 문의 화면 구현
4. 회원 탈퇴 화면 구현
5. 모임 참여 현황 화면 구현
6. 찜한 모임 화면 구현
