### ISSUE TITLE
[FEAT] 온보딩 기능 구현

### ISSUE THREAD

**Issue by youz2me** [BookJamm/FE#14]
# 📝 작업 내용
- 온보딩 화면 전환 기능 구현 
- 네비게이션 컨트롤러 삽입
- 온보딩 04 프로필 사진 설정 기능 구현
- `feature/14-onboarding-function`에서 작업

## ✔️ To-Do
- [x] 온보딩 04 프로필 사진 누르면 갤러리로 이동하게 구현
- [x] 갤러리에서 사진 선택하면 사진 바뀌게 구현
- [x] UI chevron.left 넣어둔 거 전부 삭제
- [x] 네비게이션 컨트롤러 삽입
- [x] 온보딩 02~09 연결

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
- 애플 로그인도 구현해야 함
- [[iOS] [Swift] 카메라 및 앨범 사진 가져오기](https://randy95.tistory.com/29) 
- [[Swift] 화면 스와이프 시, 뒤로가기 기능 구현하기](https://hyongdoc.tistory.com/282)
- [iOS NavigationBar 색 변경](https://hyerios.tistory.com/46)
