### ISSUE TITLE
[FEAT] 온보딩 04 UI 구현

### ISSUE THREAD

**Issue by youz2me** [BookJamm/FE#3]
# 📝 작업 내용
- 프로필 및 닉네임 설정 페이지 구현을 위한 이슈를 오픈했습니다.
- `feature/3-onboarding-4-ui` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] 뒤로 가기 버튼 구현
- [x] '프로필과 닉네임을 설정해주세요' 텍스트 구현
- [x] 프로필 사진 이미지 뷰 구현
- [x] 닉네임 설정 텍스트 필드 구현
- [x] 중복 확인 버튼 구현
- [x] 결정하기 버튼 구현

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)

**Comment by youz2me** [comment]
feature/3-onboarding-4-ui 브랜치 삭제함
