### ISSUE TITLE
[Feat] 메인 페이지 UI 구현

### ISSUE THREAD

**Issue by youz2me** [BookJamm/FE#37]
# 📝 작업 내용
- 시연영상 때 구현하지 못한 메인 페이지 UI들을 구현합니다.
  - 참여 탭에서 참여하기를 눌렀을 때 나오는 페이지를 구현합니다.
  - 메인 페이지에서 검색 창을 눌렀을 때 나오는 페이지를 구현합니다.
  - 리뷰 탭에서 인증 후 리뷰 작성하기 버튼을 눌렀을 때 나오는 페이지를 구현합니다.

## ✔️ To-Do
- [ ] 참여 탭 디테일 페이지 구현
- [ ] 검색 페이지 구현
- [ ] 리뷰 인증 페이지 구현

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
