### ISSUE TITLE
[Feat] 메인페이지 API 연결

### ISSUE THREAD

**Issue by Jangjoonmo** [BookJamm/FE#41]
# 📝 작업 내용
- 메인페이지 API 연결 이슈입니다
-  Feat/41 mainpage api 연결 에서 작업합니다

## ✔️ To-Do
- [x] 메인 페이지 내 api 연결
- [x] 독립서점 api 연결
- [x] 독립서점 테이블뷰 셀 초기화
- [x] 거리순/리뷰순/평점순 정렬
- [x] 독립서점 이미지 초기화
- [x] 독립서점 셀 클릭 시 디테일페이지 연결 초기화

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
