### ISSUE TITLE
[Feat] 친구 페이지 구현

### ISSUE THREAD

**Issue by youz2me** [BookJamm/FE#46]
# 📝 작업 내용
- 친구 페이지 UI를 구현합니다.
- `feature/46-friend-page-ui` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] 피드 메인 페이지 구현
- [x] 피드 검색 페이지 구현
- [x] 검색 결과 페이지 구현
- [x] 게시물 디테일 페이지 구현
- [x] 댓글 페이지 구현
- [x] 글 작성 플로우 구현

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
