### ISSUE TITLE
[FEAT] 온보딩 05 UI 구현

### ISSUE THREAD

**Issue by youz2me** [BookJamm/FE#5]
# 📝 작업 내용
- 친구 검색 및 추천 페이지 구현을 위한 이슈를 오픈했습니다.
- `feature/5-onboarding-5-ui` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] 뒤로 가기 버튼 구현
- [x] 'BOOKJAM을 함께 즐길 친구를 함께 찾아봐요!' 라벨 구현
- [x] 아이디로 검색하기 라벨 구현
- [x] 아이디 검색 텍스트 필드 구현
- [x] '추천 친구' 라벨 구현
- [x] 추천 친구 3명 뜨게 스택으로 구현
- [x] 완료하기 버튼 구현

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)

**Comment by youz2me** [comment]
디자인이 바뀔 때까지는 이 이상으로 구현이 힘들어서 일단 다른 화면 먼저 구현하겠습니다!
