### ISSUE TITLE
[Fix] UI 수정 및 구현 안 된 부분 추가

### ISSUE THREAD

**Issue by youz2me** [BookJamm/FE#51]
# 📝 작업 내용
- UI 중 구현하면서 빠졌던 부분을 구현합니다.
- 디자인과 다르게 구현됐던 부분을 수정합니다.
- `fix/51-amend-ui` 브랜치에서 작업합니다.

# ✔️ To-Do
- [x] 온보딩 추천 친구 부분 추가
- [x] 메인 검색 창 네비게이션 바 tintcolor 수정
- [x] 리뷰 업로드 버튼 활성화 조건 추가
- [x] 온보딩 버튼마다 활성화 조건 추가
- [x] 글 작성 페이지 검색 창 고정되는 이슈 해결
- [x] 글 작성 페이지 댓글 높이 고정되는 이슈 해결

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
