### ISSUE TITLE
[Feat] 메인디테일페이지 api 연결

### ISSUE THREAD

**Issue by Jangjoonmo** [BookJamm/FE#54]
# 📝 작업 내용
- 메인 디테일 페이지 api 연결 이슈입니다
- 작업은 feature//54-maindetail-page-api 에서 작업합니다

## ✔️ To-Do
- [x] 디테일페이지 상단 서점 이미지 연결 및 초기화
- [x] 디테일페이지 서점 정보 연결 및 초기화
- [x] 소식 api 연결 및 초기화
- [x] 참여 api 연결 및 초기화
- [x] 리뷰 api 연결 및 초기화
- [x] 책 종류 api 연결 및 초기화

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
