### ISSUE TITLE
[Feat] 온보딩02 UI 구현

### ISSUE THREAD

**Issue by Jangjoonmo** [BookJamm/FE#6]
# 📝 작업 내용
- 회원가입 화면 중 전화번호 인증 화면 구현입니다

## ✔️ To-Do
- [x] Label 2개 만들기
- [x] 전화번호 입력 텍스트 필드 만들기
- [x] 인증 요청 버튼 만들기
- [x] 인증번호 입력 텍스트 필드 만들기
- [x] 밑줄 2개 만들기
- [x] 다음으로 버튼 만들기
- [x] 제약조건 설정

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
