### ISSUE TITLE
[Test] 테스트 및 자잘한 수정

### ISSUE THREAD

**Issue by youz2me** [BookJamm/FE#65]
# 📝 작업 내용
- 데모데이 전까지 앱 테스트하면서 생기는 오류나 깜빡하고 구현 안한 부분 수정할 브랜치를 생성합니다.
- `test/65-mvp-test` 브랜치에서 작업합니다.

# ✔️ To-Do
- [x] 온보딩 테스트
- [ ] 메인 테스트
- [ ] 메인 디테일 테스트
- [ ] 피드 테스트
- [ ] 글 작성 테스트
- [x] 마이페이지 테스트

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
### 온보딩
- [x] 친구 추천 부분 바텀시트로 재구현
- [x] 비밀번호 설정 안해도 다음 페이지로 넘어가던 오류 수정
- [x] 비밀번호 설정 유효 라벨 -> 원래 계속 나오도록 구현되어 있었는데 비밀번호 입력해야 나오도록 조건 수정

### 메인
- [ ] 검색했을 때 디테일 페이지 연결이 안되어 있음

### 디테일
- [x] API 거의 다 안되는데 혹시 수정하셨던 부분인지 확인 -> 뭐지? 갑자기 됨
- [ ] 날짜 형식 맞춰서 수정

### 피드
- [ ] 검색 더미 데이터라도 삽입
- [ ] 마지막 API 서버에 물어보고 연결

### 글 작성
- [ ] 주소 검색했을 때 아무거나 나오게 해달라고 서버에 전달

### 마이페이지
- [ ] 더미 필요
- [x] 유저 페이지 사용자 이름 데이터 넘겨서 변경
- [ ] 서버에 계정 이름이랑 사진 바꿔달라고 말하기
