### ISSUE TITLE
[Feat] 지도 페이지 구현

### ISSUE THREAD

**Issue by FpRaArNkK** [BookJamm/FE#74]
# 📝 작업 내용
- LocationPageVC의 UI를 구현합니다
- feature/74-location-page-ui 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] 상단 서치바 연결
- [x] 백그라운드에 MapkitView 연결
- [x] 하단 TableView + Header/Footer 구현
- [x] 현재 위치 탐색 button 추가
- [x] Floating Panel로 목록뷰 구현
- [x] Floating Panel 세부 설정, 제스처 처리 구현

- [x] MapKit 초기화면 설정
- [x] MapKit annotation 설정 
- [x] + 위치별 핀 디자인 확인
- [x] + 핀 이벤트 핸들링 확인
- [x] MapKit Custom Annotation 설정
- [x] MapKit 클러스터링

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
- [x] 스크롤 제스처에 따른 tableView 이동 구현 - nested Scroll View
nested Scrollview (중첩된 스크롤)과 관련하여, 지도 위로 올라오는 tableView + 현재 위치 버튼의 y좌표 임계치를 설정해주어야 합니다
- [x] 상단 서치바에서 검색할 때, LocationPageVC에서 바로 검색이 진행되는지 확인 필요 (아니면 검색탭으로 진행?)
