### ISSUE TITLE
[Fix] 프로젝트 전체 수정

### ISSUE THREAD

**Issue by youz2me** [BookJamm/FE#77]
# 📝 작업 내용
- 프로젝트에서 전체적으로 디자인/기능적으로 완성도가 떨어졌던 부분을 보완합니다.
- 피그마와 다르게 구현된 부분이 있다면 수정합니다.
- 기능적으로 문제가 되는 부분이 있다면 수정합니다.
- `fix/77-project-improve` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] 홈 디자인/기능 픽스
- [ ] 디테일 디자인/기능 픽스
- [x] 피드 디자인/기능 픽스
- [x] 글 작성 디자인/기능 픽스
- [x] 마이 디자인/기능 픽스
- [x] 온보딩 디자인/기능 픽스

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
- 목요일까지는 완료하려고 하는데 이슈가 중간중간 생기면 금요일까지 미뤄질 수도 있을 것 같습니다.
