### ISSUE TITLE
[Feat] 지도 화면 API 연결

### ISSUE THREAD

**Issue by FpRaArNkK** [BookJamm/FE#80]
# 📝 작업 내용
- LocationPageVC의 API연결을 작업합니다.

## ✔️ To-Do
- [x] LocationPageVC - API - (현재 위치의) 서점 목록 불러오기
- [x] LocationPageVC - API - 현재위치에서 탐색 버튼 연결
- [x] LocationPageVC - API - 필터 버튼 연결
- [x] BookStoreListVC ~BookStoreDetailPageVC - API - 선택한 서점 디테일 보기
~~- [ ] LocationPageVC - API - (지정 위치의) 서점 목록 불러오기~~

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
- [x] MapKIt에서 특정 위치 지정에서 부근의 서점 목록 불러오기 진행할건지 확인
- [x] LocationPageVC의 서치바에서 바로 검색하여 LocationPageVC의 Mapkit에 표시되는지 확인
- [x] DB에 등록되지 않은 값들에 대한 UI처리 필요 ( 서점 이름 / 별점 / 오픈여부 )
- [x] 인기순 / 리뷰순 / 거리순 필터 - 인기순이 뭔지 파악하기

**Comment by FpRaArNkK** [comment]
struct GetPlaceResponseModel: Codable {
    let placeId: Int?
    let name: String?
    let rating: Float?
    let reviewCount: Int?
    let category: Int?
    let open: Bool?
    let images: [Image]?
    let address: Address?
    let coords: Coordinates?
}

struct Image: Codable {
    let id: Int?
    let url: String?
}

struct Address: Codable {
    let road: String
    let jibun: String?
}

struct Coordinates: Codable{
    let lat: String?
    let lon: String?
}

struct Author: Codable{
    let userId: Int?
    let username: String?
    let profileImage: String?
}

GetPlaceResponseModel에 Coords 모델 추가했습니다.
! String으로 받아옵니다 !

**Comment by FpRaArNkK** [comment]
LocationPageVC에서 디테일 뷰를 push할 때, navigationBar.isHidden이 처리되지 않는 문제가 있었습니다.

해결을 위해
BookStoreDetailPageVC에서 -

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.navigationBar.isHidden = false
    }
    
을 추가했습니다.

**Comment by FpRaArNkK** [comment]
LocationPageVC에서 디테일 뷰를 push할 때, navigationBar의 초기 상태가 보인 후 위에 stack되는 문제가 있었습니다.
(지도 화면 상단에서 BOOKJAM 로고 + 알림 아이콘이 보인 후, 뒤로 가기 버튼 바가 쌓이는게 보임)

해결을 위해
TabBarController에서 - 

 [
            mainVC,
//            locationVC,
            feedVC,
            mypageVC
        ].forEach {
            $0.navigationItem.leftBarButtonItem = titleButton
            $0.navigationItem.leftBarButtonItem?.tintColor = main03
            $0.navigationItem.setRightBarButtonItems([alertButton, settingButton], animated: true)
            $0.navigationItem.rightBarButtonItems![0].tintColor = .black
            $0.navigationItem.rightBarButtonItems![1].tintColor = .black
        }

해당 부분의 locationVC를 주석처리 했습니다.
