### ISSUE TITLE
[Feat] 지도 페이지 리파인

### ISSUE THREAD

**Issue by FpRaArNkK** [BookJamm/FE#82]
# 📝 작업 내용
데모데이 전 지도 페이지 화면을 부분적으로 리파인합니다

## ✔️ To-Do
- [x] BookStoreListVC - UI - 필터 버튼 UI 수정
- [x] LocationPageVC - API - 필터 버튼 연결
- [x] LocationPageVC - API - TableViewCell UI 분기처리
- [x] MapKit - UI - custom Annotation 디자인 수정
- [x] MapKit - Annotation - API Location array 연결하기
- [x] LocationPageVC - UI - 상단 서치바 UI 버튼으로 수정
- [x] LocationPageVC ~ SearchPageVC- 서치바 누를 때 화면 연결

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
MapKit - 핀 속성은 API 변경 전까지 bookPin으로 고정합니다 - 추후 ViewModel에서 작업 필요
LocationPageVC ~ SearchPageVC - navBar 안보이는 이슈가 있습니다.
