### ISSUE TITLE
[Build] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by youz2me** [BookJamm/FE#87]
# 📝 작업 내용
- MVVM+RxSwift 리팩토링을 위한 프로젝트 초기 세팅을 진행합니다.
- `develop` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] 코드 베이스 기반 작업
- [x] 폴더링 작업
- [x] SPM 초기 설치 작업 (RxSwift, RxAlamofire, KingFisher, SnapKit, Then)
- [x] 폰트 및 컬러 파일 추가
- [x] 익스텐션 추가
- [x] 앱 로고 추가
- [x] 스플래시 화면 추가

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
