### ISSUE TITLE
[Feat] APIManager 구현

### ISSUE THREAD

**Issue by FpRaArNkK** [BookJamm/FE#91]
# 📝 작업 내용
- APIManager를 구현합니다
- RxSwift와 Alamofire를 사용하여 추가 작업을 진행합니다.
- feature/91-APImanager 에서 작업합니다.

## ✔️ To-Do
- [x] Alamofire + Rx 로직 구현
- [x] APIEndpoint Enum케이스로 재구현
- [x] APIEndpoint - header/method/encoder를 하부 케이스로 관리
- [x] API Request 타입 통합
- [x] API DTO 구조 작업

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
- 현재 M / V / VM 구조에 대해서 논의해봐야 할 것 같습니다. Scene 분기점으로 이루어지는 각 MVVM 폴더 구조 할당은 중복 가능성의 문제점과 접근성의 저하 문제가 있어 보입니다!

- 현재 정의된 Model들은 Network - Entity에 모두 정의되어 있는데, 이를 API Connection에 사용되는 Encodable/Decodable Entity와 MVVM에서 사용하는 Model로 구분해야할 것 같습니다.

- 서버 구동 후 테스트 진행하면서 디버깅해야합니다.
